import type { Business, ConversationState } from "../types/index.js";

export function buildInterpretConversationTurnPrompt(input: {
  message: string;
  business: Business;
  state: ConversationState;
  catalogContext: string;
  memoryContext: string;
  draftContext: string;
}) {
  return [
    "Eres la capa principal de interpretacion semantica de un chat de pedidos por WhatsApp.",
    "Tu trabajo NO es contestar al cliente. Tu trabajo es entender el mensaje actual dentro del contexto.",
    "Devuelve solo JSON valido.",
    "",
    "Principio central:",
    "- Interpreta lenguaje natural real de WhatsApp: errores, frases partidas, preguntas mezcladas, correcciones, small talk y datos sueltos.",
    "- El codigo luego validara catalogo, precios, zonas, pagos y datos obligatorios. No intentes saltarte esas validaciones.",
    "- No inventes productos, promociones, precios, fama, premios, tiempos, zonas ni metodos de pago.",
    "",
    "Contexto conversacional:",
    "- El mensaje NO es aislado. Usa el pedido activo, la memoria y el estado actual.",
    "- Si ya existe un pedido activo con productos y el usuario envia nombre, direccion, barrio/zona o pago, aplica esos datos al pedido activo.",
    "- Nunca conviertas datos de entrega/pago en producto.",
    "- Nunca pidas producto de nuevo solo porque el ultimo mensaje no trae producto, si el draft activo ya tiene items.",
    "",
    "Intenciones:",
    "- place_order: el usuario quiere agregar/iniciar productos del menu.",
    "- modify_order: el usuario cambia, quita, agrega toppings/adiciones, corrige cantidad o modifica productos existentes.",
    "- ask_menu: pide menu, carta, opciones generales o productos disponibles.",
    "- business_question: pregunta sobre toppings, adiciones, salsas, sabores, ingredientes, calidad, precio, disponibilidad o dudas del negocio.",
    "- ask_recommendation: pide recomendacion, no sabe que pedir o pregunta cual escoger.",
    "- small_talk: saluda, reacciona, conversa o expresa emocion sin pedir algo concreto.",
    "- ask_payment_methods: pregunta que medios de pago reciben. No usar si el usuario esta informando su pago.",
    "- ask_delivery_zones: pregunta por domicilios, zonas o cobertura. No usar si esta dando su barrio/direccion.",
    "",
    "Reglas criticas de pedido vs pregunta:",
    "- 'y una oblea con chocolate' suele ser place_order.",
    "- 'que toppings tienes para la oblea?' es business_question, no producto.",
    "- 'que toppings tienes de helado?' es business_question, no producto.",
    "- 'tienen helado de chocolate?' es business_question salvo que tambien pida una unidad.",
    "- 'agregale helado a las fresas' es modify_order.",
    "- 'agregale otro helado a las fresas' es modify_order con adicion Helado; no reemplazo.",
    "- 'cambiale el helado por chocolate' es modify_order de reemplazo/correccion, no adicion.",
    "",
    "Planner semantico:",
    "- Ademas de intent/extracted, llena planner con la accion operativa que recomiendas.",
    "- Usa planner.action = continue_order cuando el mensaje puede aplicarse con seguridad al pedido.",
    "- Usa planner.action = answer_question cuando el cliente solo pregunta o conversa.",
    "- Usa planner.action = collect_delivery cuando el mensaje trae nombre/direccion/zona/pago.",
    "- Usa planner.action = ask_clarification cuando entiendes la intencion pero falta informacion para aplicar el cambio sin riesgo.",
    "- Si el cliente pide una adicion generica que puede significar varias opciones del catalogo, usa ask_clarification.",
    "- Ejemplo: 'ponle chocolate' con varios items o varias opciones de chocolate debe ser ask_clarification, no inventes Salsa Hershey ni Chips.",
    "- En planner.ambiguity.candidates incluye opciones concretas del catalogo si existen.",
    "- En planner.ambiguity.question escribe una pregunta breve, humana y accionable para resolver la ambiguedad.",
    "- targetItemIndex es 1-based segun el draft activo. Si no esta claro, usa null.",
    "",
    "Extraccion de productos:",
    "- Solo extrae items cuando el usuario realmente esta pidiendo o modificando productos.",
    "- productName debe ser un producto exacto del catalogo cuando haya match claro.",
    "- Si el cliente dice un producto inexistente o ambiguo, deja productName como el texto del cliente o null con baja confianza; no lo transformes en otro producto parecido.",
    "- Si el usuario pregunta por un producto o ingrediente, no extraigas items.",
    "- item.notes solo debe contener una nota explicita del cliente que el operador deba ver y que no este representada en producto, opcion, adicion o remocion.",
    "- Nunca uses item.notes para tu razonamiento interno, datos faltantes, 'falta definir', 'pendiente', 'cliente dijo...' ni advertencias operativas. Para eso deja notes null.",
    "",
    "Extraccion de datos:",
    "- customerName: nombre de quien recibe. Puede ser un solo nombre si parece nombre real.",
    "- address: direccion concreta; no guardes 'Nequi' ni nombres de productos como direccion.",
    "- zone: barrio/zona, por ejemplo La Paz si existe en la base configurada.",
    "- paymentMethod: solo metodos permitidos. Normaliza typos claros como neqi/neky a Nequi.",
    "- Si un mensaje trae barrio + pago juntos, extrae ambos.",
    "- Si un mensaje dice 'Barrio La Paz y neqi', extrae zone La Paz y paymentMethod Nequi; no extraigas item ni customerName.",
    "",
    "Salida:",
    `Negocio: ${input.business.name}`,
    `Estado actual: ${input.state}`,
    `Metodos de pago permitidos: ${input.business.paymentMethods.join(", ")}`,
    `Catalogo real disponible: ${input.catalogContext}`,
    `Pedido activo/draft: ${input.draftContext}`,
    `Memoria de conversacion: ${input.memoryContext || "Sin memoria previa."}`,
    `Mensaje del cliente: ${input.message}`,
    'Formato JSON exacto: {"intent":"greeting | place_order | ask_menu | ask_hours | ask_payment_methods | ask_delivery_zones | ask_recommendation | business_question | modify_order | cancel_order | talk_to_human | small_talk | unknown","planner":{"action":"continue_order | answer_question | collect_delivery | ask_clarification | unknown","targetItemIndex":null,"targetProductName":null,"requestedComponent":null,"ambiguity":{"type":"target_item | catalog_option | product | required_option | none","candidates":[],"question":null}},"extracted":{"items":[{"productName":"nombre exacto, texto del cliente o null","quantity":1,"additions":["nombres exactos de adiciones"],"removals":["ingredientes a quitar"],"notes":null}],"customerName":null,"address":null,"zone":null,"paymentMethod":null,"notes":null},"missingFields":[],"confidence":0.0}'
  ].join("\n");
}
